### ISSUE TITLE
Not see 1.12 5875

### ISSUE THREAD

**Issue by shikulja** [Abd-ulRahman/WDB2XEditor#3]
Not see 1.12 5875
<img width="219" alt="image" src="https://user-images.githubusercontent.com/3386359/203001366-aa44828f-3101-4a76-bfa6-5dff29ee54ac.png">

<img width="571" alt="image" src="https://user-images.githubusercontent.com/3386359/203001529-e0bb776b-4107-4827-ba4c-407f2b3b6ba6.png">

WoWDBDefs has been added too

**Comment by Abd-ulRahman** [comment]
Use this old [WoWDBDefs] as it has 1.12.5875
https://github.com/wowdev/WoWDBDefs/tree/c63be792d176a107797beb8425993fa8bddfa197
It does Support the following Only
SpellEffectNames.dbd
CharacterCreateCameras.dbd
UISoundLookups.dbd
CharVariations.dbd
SpellAuraNames.dbd
AttackAnimTypes.dbd
SoundCharacterMacroLines.dbd
SheatheSoundLookups.dbd
schlumpf/AnimationData
schlumpf/CreatureModelData
PetLoyalty.dbd
schlumpf/Map
Map.dbd
