### ISSUE TITLE
Dragonflight 10.2.5 support?

### ISSUE THREAD

**Issue by Aztec2012** [Abd-ulRahman/WDB2XEditor#6]
Dragonflight 10.2.5 support?

**Comment by Abd-ulRahman** [comment]
WoWDBDefs  now support  10.2.5.52983  at  https://github.com/wowdev/WoWDBDefs/tree/master/definitions
https://github.com/wowdev/WoWDBDefs
And if you may extract db as db2 it should support it.

**Comment by Abd-ulRahman** [comment]
https://github.com/wowdev/WoWDBDefs/commit/2879b489835c7016665db18eabc08b4718d95085
